services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - path: ./backend/.env
        required: false
    volumes:
      - ./backend:/opt/app
    restart: unless-stopped

# vim: ft=yaml.docker-compose
