services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - path: ./backend/.env
        required: true
    depends_on:
      - backend
    restart: unless-stopped
    container_name: web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: ./backend/.env
        required: true
    volumes:
      - ./backend:/opt/app
    restart: unless-stopped
    container_name: backend

# vim: ft=yaml.docker-compose
